services:
  inference:
    container_name: inference
    build:
      context: .
      dockerfile: Dockerfile
    command: python -u /app/app.py
    ports:
      - "9191:9191"

  worker:
    container_name: worker
    image: alloranetwork/allora-offchain-node:v0.5.1
    volumes:
      - ./worker-data:/data
    depends_on:
      - inference
    env_file:
      - ./worker-data/env_file
  
volumes:
  inference-data:
  worker-data:
